// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestString struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestString) Reset()         { *m = RequestString{} }
func (m *RequestString) String() string { return proto.CompactTextString(m) }
func (*RequestString) ProtoMessage()    {}
func (*RequestString) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RequestString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestString.Unmarshal(m, b)
}
func (m *RequestString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestString.Marshal(b, m, deterministic)
}
func (m *RequestString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestString.Merge(m, src)
}
func (m *RequestString) XXX_Size() int {
	return xxx_messageInfo_RequestString.Size(m)
}
func (m *RequestString) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestString.DiscardUnknown(m)
}

var xxx_messageInfo_RequestString proto.InternalMessageInfo

func (m *RequestString) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type ResponseString struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool     `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseString) Reset()         { *m = ResponseString{} }
func (m *ResponseString) String() string { return proto.CompactTextString(m) }
func (*ResponseString) ProtoMessage()    {}
func (*ResponseString) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ResponseString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseString.Unmarshal(m, b)
}
func (m *ResponseString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseString.Marshal(b, m, deterministic)
}
func (m *ResponseString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseString.Merge(m, src)
}
func (m *ResponseString) XXX_Size() int {
	return xxx_messageInfo_ResponseString.Size(m)
}
func (m *ResponseString) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseString.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseString proto.InternalMessageInfo

func (m *ResponseString) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseString) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func init() {
	proto.RegisterType((*RequestString)(nil), "RequestString")
	proto.RegisterType((*ResponseString)(nil), "ResponseString")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe6, 0xe2, 0x0d, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x17, 0x12, 0xe2, 0x62, 0x49, 0x49,
	0x2c, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x1c, 0xb8, 0xf8, 0x82,
	0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xa1, 0xaa, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b,
	0x13, 0xd3, 0x61, 0x0a, 0x61, 0x5c, 0x21, 0x11, 0x2e, 0xd6, 0xd4, 0xa2, 0xa2, 0xfc, 0x22, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x08, 0xc7, 0xc8, 0x9d, 0x8b, 0xdf, 0x2f, 0xb1, 0x38, 0xd1,
	0xb5, 0x20, 0x33, 0x39, 0x18, 0x62, 0xbf, 0x90, 0x09, 0x17, 0xbf, 0x4b, 0x7e, 0x79, 0x5e, 0x4e,
	0x7e, 0x62, 0x8a, 0x5f, 0x62, 0x49, 0x69, 0x51, 0x62, 0x8e, 0x10, 0x9f, 0x1e, 0x8a, 0x5b, 0xa4,
	0xf8, 0xf5, 0x50, 0xad, 0x55, 0x62, 0x48, 0x62, 0x03, 0x3b, 0xdb, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x4a, 0xcb, 0x36, 0x09, 0xc7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NasaEpicServiceClient is the client API for NasaEpicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NasaEpicServiceClient interface {
	DownloadNatural(ctx context.Context, in *RequestString, opts ...grpc.CallOption) (*ResponseString, error)
}

type nasaEpicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNasaEpicServiceClient(cc grpc.ClientConnInterface) NasaEpicServiceClient {
	return &nasaEpicServiceClient{cc}
}

func (c *nasaEpicServiceClient) DownloadNatural(ctx context.Context, in *RequestString, opts ...grpc.CallOption) (*ResponseString, error) {
	out := new(ResponseString)
	err := c.cc.Invoke(ctx, "/NasaEpicService/DownloadNatural", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NasaEpicServiceServer is the server API for NasaEpicService service.
type NasaEpicServiceServer interface {
	DownloadNatural(context.Context, *RequestString) (*ResponseString, error)
}

// UnimplementedNasaEpicServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNasaEpicServiceServer struct {
}

func (*UnimplementedNasaEpicServiceServer) DownloadNatural(ctx context.Context, req *RequestString) (*ResponseString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadNatural not implemented")
}

func RegisterNasaEpicServiceServer(s *grpc.Server, srv NasaEpicServiceServer) {
	s.RegisterService(&_NasaEpicService_serviceDesc, srv)
}

func _NasaEpicService_DownloadNatural_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NasaEpicServiceServer).DownloadNatural(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NasaEpicService/DownloadNatural",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NasaEpicServiceServer).DownloadNatural(ctx, req.(*RequestString))
	}
	return interceptor(ctx, in, info, handler)
}

var _NasaEpicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NasaEpicService",
	HandlerType: (*NasaEpicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DownloadNatural",
			Handler:    _NasaEpicService_DownloadNatural_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
